os:
  - linux
  - osx

dist: xenial

addons:
    apt:
        packages:
            - cmake
            - libchromaprint-dev
    homebrew:
        packages:
            - gnu-sed
            - cmake
            - chromaprint
            - pkg-config
git:
    submodules: false

language: rust

rust:
    - stable
    - beta
    - nightly

matrix:
    allow_failures:
        - rust: nightly

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sed_bin="gsed"; else sed_bin="sed"; fi
    - $sed_bin -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
script:
    - cargo build
    - cargo test
    #- cargo build --no-default-features --features=static
    #- cargo test --no-default-features --features=static
    - cargo build --release
    - cargo test --release
    #- cargo build --release --no-default-features --features=static
    #- cargo test --release --no-default-features --features=static

cache: cargo

before_cache:
  # Travis can't cache files that are not readable by "others"
    - chmod -R a+r $HOME/.cargo

branches:
    only:
        - master

notifications:
    email:
        on_success: never
