name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]
jobs:
  build-link:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Nix
        uses: cachix/install-nix-action@v7
      - name: Format
        run: nix-shell --run "cargo fmt --all -- --check"
      - name: Build
        run: nix-shell --run "cargo build"
      - name: Clippy
        run: nix-shell --run "cargo clippy -- -D warnings"
      - name: Test
        run: nix-shell --run "cargo test"
  build-vendor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Nix
        uses: cachix/install-nix-action@v7
      - name: Format
        run: nix-shell --run "cargo fmt --all -- --check"
      - name: Build
        run: nix-shell --run "cargo build --features vendor"
      - name: Clippy
        run: nix-shell --run "cargo clippy --features vendor -- -D warnings"
      - name: Test
        run: nix-shell --run "cargo test --features vendor"
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Nix
        uses: cachix/install-nix-action@v7
      - name: Build
        run: nix-build -A chromaprint_sys
  nix-shell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Nix
        uses: cachix/install-nix-action@v7
      - name: Build
        run: nix-build -A shellBuildInputs
